[package]
name = "rp-schotter"
version = "0.1.0"
authors = ["Armando Perez <armando@roastery.com>"]

[dependencies]
find_folder = "^0.3"
piston_window = "^0.80"
pistoncore-sdl2_window = "^0.50"
rand = "^0.5"

[profile.release]
lto = true
debug-assertions = false
codegen-units = 1

